on:
    pull_request:
        branches: main
    schedule:
      - cron: '25 2 * * 6'
jobs:
    code-checks:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Install front end dependencies
          run: python3.12 -m install_front_end_deps
        - name: Install python packages
          run: |
            python3.12 -m pip install --upgrade pip
            python3.12 -m pip install -r requirements-dev.txt
        - name: Run code checks
          run: ./code_checks.sh
