on:
    pull_request:
        branches: main
    schedule:
      - cron: '25 2 * * 6'
jobs:
    code-checks:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Enable KVM group perms # https://github.com/actions/runner-images/issues/7670
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3
          with:
            packages: 'platform-tools emulator'
            cmdline-tools-version: 11076708
            log-accepted-android-sdk-licenses: false
        - name: Install Android Virtual Device Image
          run: sdkmanager "system-images;android-35;google_apis_playstore;x86_64"
        - name: Install Android Virtual Device
          run: echo no | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n Pytest_AVD -k "system-images;android-35;google_apis_playstore;x86_64"
        - name: Run AVD in background
          run: $ANDROID_HOME/emulator/emulator -avd Pytest_AVD -no-window -metrics-collection &
        - run: npm install -g appium
          name: Install appium
        - name: Install UIAutomator2
          run: appium driver install uiautomator2
        - name: Check UIAutomator2 installation
          run: appium driver doctor uiautomator2
        - name: Run appium server in the background
          run: appium --allow-insecure chromedriver_autodownload >> ${{ runner.temp }}/appium.log &
        - name: Install python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Install front end dependencies
          run: python3.12 -m install_front_end_deps
        - name: Install python packages
          run: |
            python3.12 -m pip install --upgrade pip
            python3.12 -m pip install -r requirements-dev.txt
        - name: Setup reverse proxy for AVD
          run: $ANDROID_HOME/platform-tools/adb reverse tcp:5000 tcp:5000
        - name: Run code checks
          run: ./code_checks.sh
        - name: Show appium log
          if: failure()
          run: cat ${{ runner.temp }}/appium.log
