on:
    schedule:
      - cron: '20 2 * * 6'
jobs:
    header-check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - name: Install python packages
          run: |
            python3.13 -m ensurepip --upgrade
            python3.13 -m pip install requests
        - name: Check website headers
          run: python3.13 tests/http_obs.py
